# Generated by Django 4.1.2 on 2022-10-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roshitaappnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeeksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='roshitamodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='roshitamodel',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
