# Generated by Django 4.1.2 on 2022-10-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roshitaappnew', '0002_geeksmodel_remove_roshitamodel_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoshitaModel',
        ),
    ]
